export MASTER_ADDR=IP_ADDRESS
export MASTER_PORT=FREE_PORT
export OMP_NUM_THREADS=1
export USE_SIMPLE_THREADED_LEVEL3=1
export CUDA_VISIBLE_DEVICES=GPU_NUMBERS
TOKENIZERS_PARALLELISM=false
python src/main.py \
    --mode="test" \
    --task="entity recognition" \
    --dataset="multiwoz" \
    --model_name="bert-base-uncased" \
    --ckpt_dir="saved_models" \
    --data_dir="data" \
    --processed_dir="processed" \
    --class_dict_name="class_dict" \
    --train_prefix="train" \
    --valid_prefix="valid" \
    --test_prefix="test" \
    --utter_name="utter" \
    --label_name="label" \
    --entity_dir="entity" \
    --action_dir="action" \
    --max_len=512 \
    --max_times=5 \
    --num_epochs=50 \
    --batch_size=32 \
    --num_workers=16 \
    --learning_rate=5e-5 \
    --factor=0.1 \
    --max_grad_norm=1.0 \
    --patience=3 \
    --threshold=1e-3 \
    --sigmoid_threshold=0.5 \
