python src/pretrain.py \
    --default_root_dir="./" \
    --shuffled_dir="data/pretrain_shuffled" \
    --num_epochs=1 \
    --batch_size=32 \
    --num_workers=4 \
    --learning_rate=2e-5 \
    --warmup_ratio=0.1 \
    --save_interval=50000 \
    --log_interval=10000 \
    --max_grad_norm=1.0 \
    --seed=0 \
    --pooling="cls" \
    --amp_level="O1" \
    --gpus="0" \
    --num_nodes=1
