python src/finetune.py \
    --task="intent" \
    --dataset="oos" \
    --cache_dir="cached" \
    --data_dir="data" \
    --finetune_dir="finetune" \
    --class_dict_name="class_dict" \
    --train_prefix="train" \
    --valid_prefix="valid" \
    --test_prefix="test" \
    --max_turns=1 \
    --num_epochs=20 \
    --batch_size=16 \
    --num_workers=4 \
    --max_encoder_len=512 \
    --learning_rate=5e-5 \
    --warmup_prop=0 \
    --max_grad_norm=1.0 \
    --sigmoid_threshold=0.5 \
    --seed=0 \
    --model_name="dialogsentbert-max" \
    --pooling="max" \
    --gpu="0" \
    --num_nodes=1 \
    --ckpt_dir="saved_models" \
    --ckpt_name="bert_max_epoch=3_train_acc=0.9261_valid_acc=0.8686"