export MASTER_ADDR=FREE_ADDR
export MASTER_PORT=FREE_PORT
export OMP_NUM_THREADS=1
export USE_SIMPLE_THREADED_LEVEL3=1
export CUDA_VISIBLE_DEVICES=GPU_NUMBER
TOKENIZERS_PARALLELISM=false
python src/main.py \
    --mode="train" \
    --task="entity recognition" \
    --dataset="multiwoz" \
    --model_name="bert-base-uncased" \
    --ckpt_dir="saved_models" \
    --data_dir="data" \
    --processed_dir="processed" \
    --class_dict_name="class_dict" \
    --train_prefix="train" \
    --valid_prefix="valid" \
    --utter_name="utter" \
    --label_name="label" \
    --entity_dir="entity" \
    --action_dir="action" \
    --max_len=51 \
    --max_times=1 \
    --num_epochs=50 \
    --batch_size=8 \
    --num_workers=4 \
    --learning_rate=2e-5 \
    --warmup_prop=0.1 \
    --max_grad_norm=1.0 \
    --sigmoid_threshold=0.5 \
    --compressed="no" \
    --cached="no" \
    --model_seed=0 \
    --data_seed=0 \
    --nodes=1 \
    --gpus=1 \
    --rank=0